# -*- coding: utf-8 -*-
"""PRODIGY_DS_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jWEJ-bfEV9LUJK8ara9elnLOELh3Mm7U
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel("/content/WorldBank Data.xlsx")
data.head()

data.tail()

data.columns

data.shape

data.size

data.index

data.describe()

data1=data.dropna()
data1.head()

data1.isna().sum()

data1.info()

year = 2012
variable = 'Life expectancy at birth (years)'

data_year = data[data['Year'] == year]

#Create A Histogram

plt.figure(figsize=(10, 6))
plt.hist(data_year[variable], bins=20, edgecolor='k', alpha=0.7)
plt.title(f'Distribution of {variable} in {year}')
plt.xlabel(variable)
plt.ylabel('Frequency')
plt.show()

# Customize the plot further
plt.title(f'Distribution of {variable} in {year}')
plt.xlabel(variable)
plt.ylabel('Frequency')
plt.grid(True, linestyle='--', alpha=0.7)

# Add labels for mean and median
mean_value = data_year[variable].mean()
median_value = data_year[variable].median()
plt.axvline(mean_value, color='red', linestyle='dashed', linewidth=2, label=f'Mean: {mean_value:.2f}')
plt.axvline(median_value, color='green', linestyle='dashed', linewidth=2, label=f'Median: {median_value:.2f}')
plt.legend()
plt.show()

region_counts = data['Region'].value_counts()

# Create a bar chart
plt.figure(figsize=(10, 6))
region_counts.plot(kind='bar', color='skyblue')
plt.xlabel('Region')
plt.ylabel('Number of Countries')
plt.title('Distribution of Countries by Region')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(15, 6))
plt.subplot(1, 2, 2)
region_percentage = (region_counts / region_counts.sum()) * 100
colors = ['gold', 'lightcoral', 'lightgreen', 'lightskyblue']
region_percentage.plot(kind='pie', autopct='%1.1f%%', colors=colors)
plt.axis('equal')
plt.title('Distribution of Countries by Region (Percentage)')
plt.tight_layout()
plt.show()